import { Fragment } from "react";
import Head from "next/head";
import SidebarLayout from "../../../components/dashboard/SidebarLayout";
import CreateCourse from "../../../components/dashboard/course/CreateCourse";

const Create = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex  items-center justify-between bg-violet-600 px-4 py-3 rounded-md shadow">
          <h2 className="text-xl lg:text-3xl font-bold tracking-wider ">
            Create Course
          </h2>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-5 w-5 text-pink-600"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" />
          </svg>
        </div>
        <div className="">
          <CreateCourse />
        </div>
      </div>
    </Fragment>
  );
};

Create.PageLayout = SidebarLayout;
export default Create;
