import Head from "next/head";
import { withSSRContext, Auth, API } from "aws-amplify";
import { listResources } from "../src/graphql/queries";
import HeroSection from "../components/home/HeroSection";
import TeamSection from "../components/home/TeamSection";
import ReactSection from "../components/home/ReactSection";
import FrontEndSection from "../components/home/FrontEndSection";
import BuildSection from "../components/home/BuildSection";
import BackendSection from "../components/home/BackendSection";
import Footer from "../components/footer/Footer";
import FramerMotion from "../components/sharedLayouts/FramerMotion";

export default function Home({ resources }) {
  var heroResources = resources.filter(function (item) {
    return item.section === "hero";
  });
  var teamResources = resources.filter(function (item) {
    return item.section === "team";
  });
  var sectionSecond = resources.filter(function (item) {
    return item.section === "second";
  });
  var frontendResources = resources.filter(function (item) {
    return item.section === "frontend";
  });
  var beckendResources = resources.filter(function (item) {
    return item.section === "backend";
  });

  return (
    <FramerMotion>
      <div>
        <Head>
          <title>WebMolecule</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="min-h-screen w-full bg-[url('/graph-paper.svg')] bg-cover ">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 space-y-32 md:space-y-48 h-full">
            <section className="">
              <HeroSection heroResources={heroResources} />
            </section>
            <section>

              <ReactSection sectionSecond={sectionSecond} />

            </section>
            <section>

              <FrontEndSection frontendResources={frontendResources} />

            </section>
            <section>

              <BuildSection frontendResources={frontendResources} />

            </section>
            <section>

              <BackendSection beckendResources={beckendResources} />

            </section>
            <section>

              <TeamSection teamResources={teamResources} />

            </section>
          </div>
          <section>
            <Footer />
          </section>
        </div>
      </div>
    </FramerMotion>
  );
}

export const getStaticProps = async (context) => {
  const SSR = withSSRContext();
  const { data } = await SSR.API.graphql({
    query: listResources,
    // authMode: "AWS_IAM",
  });

  return {
    props: {
      resources: data.listResources.items,
    },
  };
};
