import Head from "next/head";
import { Fragment } from "react";
import { withSSRContext, API, Storage } from "aws-amplify";
import { useState, useEffect } from "react";
import Sidebar from "../../components/courses/Sidebar";
import { listCourses } from "../../src/graphql/queries";

export const getServerSideProps = async (ctx) => {
  const req = ctx.req;
  console.log("serverReqCTX", ctx);
  const SSR = withSSRContext(ctx.req);
  let filter = {
    category: {
      eq: ctx.query.name,
    },
  };
  const response = await SSR.API.graphql({
    query: listCourses,
    variables: {
      filter: filter,
    },

    authMode: "AWS_IAM",
  });
  return {
    props: {
      initialCourses: response.data.listCourses.items,
      initialToken: response.data.listCourses.nextToken,
    },
  };
};

const Course = ({ initialCourses }) => {
  console.log("initialCourses", initialCourses);
  return (
    <Fragment>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto mt-9 max-w-7xl px-4 sm:px-6 lg:mt-16">
        <div className="grid-cols-4  gap-20 lg:grid ">
          <div className=" col-span-1 hidden lg:block">
            <Sidebar />
          </div>
          <main className="col-span-3">
            {initialCourses.map((course) => (
              <div key={course.id}>
                <h1>{course.title}</h1>
                <p>{course.description}</p>
              </div>
            ))}
          </main>
        </div>
        <div>heloo</div>
      </div>
    </Fragment>
  );
};

export default Course;
