import Head from "next/head";
import { Fragment } from "react";
import { useRouter } from "next/router";

const Course = () => {
  const { query } = useRouter();
  return (
    <Fragment>
      <Head>
        <title>Courses | {query.param}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto mt-9 max-w-7xl px-4 sm:px-6 lg:mt-16">
        {query.param}
      </div>
    </Fragment>
  );
};

export default Course;
