import { Fragment } from "react";
import Head from "next/head";
import SidebarLayout from "../../components/dashboard/SidebarLayout";
import UserTable from "../../components/user/UserTable";

const ViewUsers = () => {
  return (
    <Fragment>
      <Head>
        <title>Dashboard | Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <h1 className="text-center tracking-wider leading-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-xl font-bold rounded-md shadow-md px-4 py-3">
          User List
        </h1>
        <div className="mt-12">
          <UserTable />
        </div>
      </div>
    </Fragment>
  );
};
ViewUsers.PageLayout = SidebarLayout;

export default ViewUsers;
